version: '3.8'

services:
  server:
    build: ./server
    container_name: rps_server
    ports:
      - "12345:12345"

  proxy:
    build: ./proxy
    container_name: rps_proxy
    depends_on:
      - server
    ports:
      - "8080:8080"

  client:
    build: ./client
    container_name: rps_client
    depends_on:
      - proxy
    ports:
      - "80:80"
